/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Sora Prework App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost:10010".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    message: string;
}

/**
 * 
 * @export
 * @interface HotelPriceAverageResponse
 */
export interface HotelPriceAverageResponse {
    /**
     * 
     * @type {string}
     * @memberof HotelPriceAverageResponse
     */
    hotelName: string;
    /**
     * 
     * @type {string}
     * @memberof HotelPriceAverageResponse
     */
    planName: string;
    /**
     * 
     * @type {string}
     * @memberof HotelPriceAverageResponse
     */
    planDetail: string;
    /**
     * 
     * @type {number}
     * @memberof HotelPriceAverageResponse
     */
    average: number;
}


/**
 * HotelsApi - fetch parameter creator
 * @export
 */
export const HotelsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns averages to the caller
         * @param {number} targetMonth The year and month
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        averagePricesPerPlan(targetMonth: number, options: any = {}): FetchArgs {
            // verify required parameter 'targetMonth' is not null or undefined
            if (targetMonth === null || targetMonth === undefined) {
                throw new RequiredError('targetMonth','Required parameter targetMonth was null or undefined when calling averagePricesPerPlan.');
            }
            const localVarPath = `/hotels/plans/prices/average`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (targetMonth !== undefined) {
                localVarQueryParameter['targetMonth'] = targetMonth;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HotelsApi - functional programming interface
 * @export
 */
export const HotelsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Returns averages to the caller
         * @param {number} targetMonth The year and month
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        averagePricesPerPlan(targetMonth: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<HotelPriceAverageResponse>> {
            const localVarFetchArgs = HotelsApiFetchParamCreator(configuration).averagePricesPerPlan(targetMonth, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * HotelsApi - factory interface
 * @export
 */
export const HotelsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Returns averages to the caller
         * @param {number} targetMonth The year and month
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        averagePricesPerPlan(targetMonth: number, options?: any) {
            return HotelsApiFp(configuration).averagePricesPerPlan(targetMonth, options)(fetch, basePath);
        },
    };
};

/**
 * HotelsApi - object-oriented interface
 * @export
 * @class HotelsApi
 * @extends {BaseAPI}
 */
export class HotelsApi extends BaseAPI {
    /**
     * Returns averages to the caller
     * @param {number} targetMonth The year and month
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HotelsApi
     */
    public averagePricesPerPlan(targetMonth: number, options?: any) {
        return HotelsApiFp(this.configuration).averagePricesPerPlan(targetMonth, options)(this.fetch, this.basePath);
    }

}

